import os
from torch.utils.data import Sampler
from torch.utils.data import DataLoader
from enum import Enum
import numpy as np
import random
import torch
#from sabdab_dgad import SAbDabDatasetDgad
from diffab.datasets import get_dataset
from diffab.datasets.dgad_aux import AuxDataset, AuxCollate

from diffab.utils.misc import *
from diffab.utils.data import *
from diffab.utils.train import *

from collections import Counter
from easydict import EasyDict
from tqdm import tqdm

# Sampling method enum
class SamplingMixingMethod(Enum):
    LINEAR = "linear"
    EXPONENTIAL = "exponential"



#
# CUSTOM SAMPLERS
#

class BalancedClusterSampler(Sampler):
    """
    Custom sampler for balanced, coverage-guaranteed, and oversampled cluster sampling.
    
    This sampler generates a fixed-length sequence of sample indices for each epoch, with:
      - Coverage guarantee: every sample is seen at least once per epoch.
      - Oversampling: large clusters are sampled more often, according to a tunable probability distribution.
      - Flexible mixing: choose between linear interpolation and exponential (power-law) scaling for cluster probabilities.
      - Fixed epoch size: total samples per epoch = multiplier × dataset size.
      - Reproducible sampling: uses local random generators and seed per epoch.
    
    Sampling methods:
      - LINEAR: Interpolates between original cluster distribution and uniform distribution.
      - EXPONENTIAL: Uses power-law scaling (e.g., Word2Vec negative sampling).
    
    Args:
        dataset: Dataset with cluster information (must have id_to_cluster mapping and ids_in_split).
        sampling_balance (float): Controls balance between original and uniform sampling.
            - 1.0: Original cluster distribution (proportional to cluster sizes)
            - 0.0: Uniform distribution across clusters
            - 0.75: Recommended starting point (Word2Vec standard for exponential)
        sampling_mixing (SamplingMixingMethod): Method for probability calculation.
            - LINEAR: sampling_balance * original + (1-sampling_balance) * uniform
            - EXPONENTIAL: cluster_size^sampling_balance (power-law scaling)
        multiplier (int): Number of times the dataset size to set the epoch length (e.g., 30 for robust coverage).
        seed (int): Random seed for reproducible sampling.
    
    Design notes:
      - Sequence is generated by sampling clusters according to probabilities, then samples within clusters, with replacement.
      - Any missing samples (not picked) are inserted by replacing duplicates, ensuring coverage without changing epoch length.
      - Final sequence is shuffled for randomness and distributed among workers if using DataLoader with num_workers > 1.
    """


    def __init__(self,dataset, sampling_balance=0.75, sampling_mixing=SamplingMixingMethod.LINEAR,multiplier=30,  seed=70):
        super().__init__(dataset)
        self.dataset = dataset
        self.sampling_balance = sampling_balance
        self.sampling_mixing = sampling_mixing
        self.multiplier = multiplier

        self.seed = seed

        print('BalancedClusterSampler: Initializing with:')
        print(f' - sampling_balance: {sampling_balance}')
        print(f' - sampling_mixing: {sampling_mixing}')
        print(f' - multiplier: {multiplier}')
        print(f' - seed: {seed}')

        #This will be the actual epoch size, it will be bigger than the orgina dataset since there is oversampling to account for
        #the cluster distribution based on sample balance while ensuring full coverage of all samples.
        self.epoch_size = len(self.dataset) * self.multiplier

        #Check if sampling_mixing is a string, if so convert to enum
        if isinstance(sampling_mixing, str):
            sampling_mixing_str_to_enum = { 
                'linear': SamplingMixingMethod.LINEAR,
                'exponential': SamplingMixingMethod.EXPONENTIAL
            }
            self.sampling_mixing = sampling_mixing_str_to_enum.get(sampling_mixing.lower())


        # Build cluster mapping  'clusteris': [0, 1, 3, 7 ...], the elements is the idx of the ids_in_split
        self.cluster_to_indices = {}
        for idx, sample_id in enumerate(dataset.ids_in_split):
            cluster_id = dataset.id_to_cluster[sample_id]
            if cluster_id not in self.cluster_to_indices:
                self.cluster_to_indices[cluster_id] = []
            self.cluster_to_indices[cluster_id].append(idx)
        
        self.unique_clusters = list(self.cluster_to_indices.keys())
        if self.sampling_mixing == SamplingMixingMethod.LINEAR:
            self._calculate_probabilities_for_linear()
        elif self.sampling_mixing == SamplingMixingMethod.EXPONENTIAL:
            self._calculate_probabilities_for_exponential()


    def _calculate_probabilities_for_linear(self):
        """Calculate cluster probabilities based on the sampling balance."""
        cluster_sizes = np.array([len(self.cluster_to_indices[cluster_id]) for cluster_id in self.unique_clusters])
        original_probs = cluster_sizes / cluster_sizes.sum()
        flat_probs = np.ones(len(self.unique_clusters)) / len(self.unique_clusters)
        self.cluster_probs = self.sampling_balance * original_probs + (1-self.sampling_balance) * flat_probs

    def _calculate_probabilities_for_exponential(self):
        cluster_sizes = np.array([len(self.cluster_to_indices[cluster_id]) for cluster_id in self.unique_clusters])
        powered_sizes = np.power(cluster_sizes, self.sampling_balance)
        self.cluster_probs = powered_sizes / np.sum(powered_sizes)
        pass
    
    def __iter__(self):
        # Epoch-based seeding (crucial for different orders each epoch)
        rng_py = random.Random((self.seed or 0) + self.epoch)
        rng_np = np.random.default_rng((self.seed or 0) + self.epoch)
        #np.random.seed((self.seed or 0) + self.epoch)

        # Generate complete balanced sequence
        full_sequence = self._generate_balanced_sequence(rng_py, rng_np)
        
        #No need to do splitting logic here, since the DataLoader will handle it.
        # Auto-split among workers (no worker-specific logic needed!)
        #worker_info = torch.utils.data.get_worker_info()
        #print(worker_info)
        # if worker_info is None:
        #     return iter(full_sequence)
        # else:
        #     worker_id = worker_info.id
        #     num_workers = worker_info.num_workers
        #     worker_indices = full_sequence[worker_id::num_workers]
        #     return iter(worker_indices)

        return iter(full_sequence)

    def _generate_balanced_sequence(self, rng_py, rng_np): 
        """Generate fixed-length balanced sequence with coverage guarantee."""

        # Step 1: Sample clusters according to probabilities, with replacement

        print('Picking clusters')
        chosen_clusters = rng_np.choice(self.unique_clusters, 
                                   size=self.epoch_size, 
                                   p=self.cluster_probs)

        sampled_indices = []
        for chosen_cluster_id in tqdm(chosen_clusters, desc='generating balanced sequence'):
            #chosen_cluster_id = rng_np.choice(self.unique_clusters, p=self.cluster_probs)
            # Pick a random sample from the chosen cluster (with replacement)
            sample_idx = rng_np.choice(self.cluster_to_indices[chosen_cluster_id])
            sampled_indices.append(sample_idx)

        # Step 2: Coverage guarantee - find missing samples
        all_indices = set(range(len(self.dataset)))
        seen = set(sampled_indices)
        missing = list(all_indices - seen)

        # Step 3: Replace duplicates with missing samples
        counts = Counter(sampled_indices)
        replace_positions = [i for i, idx in enumerate(sampled_indices) if counts[idx] > 1]
        for miss_idx, pos in zip(missing, replace_positions):
            counts[sampled_indices[pos]] -= 1
            sampled_indices[pos] = miss_idx
            counts[miss_idx] += 1

        # Step 4: Shuffle for randomness
        rng_py.shuffle(sampled_indices)
        return sampled_indices



    def _generate_balanced_sequence_old(self): 
        """Generate complete balanced sequence with coverage guarantee."""

        #Create a copu of the clusters
        cluster_pools = {cluster_id: list(indices) for cluster_id, indices in self.cluster_to_indices.items()}
        
        # Shuffle within clusters
        for pool in cluster_pools.values():
            random.shuffle(pool)
        
        result_indices = []
        remaining = {cluster_id: len(pool) for cluster_id, pool in cluster_pools.items()}
        
        while sum(remaining.values()) > 0:
            
            # Available cluster ids
            available = [cluster_id for cluster_id in self.unique_clusters if remaining[cluster_id] > 0]
            if not available:
                break
            
            # Probabilities for available clusters
            probs = [self.cluster_probs[self.unique_clusters.index(cluster_id)] for cluster_id in available]
            #Renormalize probabilities
            probs = np.array(probs) / sum(probs)
            
            # Choose cluster and sample
            chosen_cluster_id = np.random.choice(available, p=probs)
            sample_idx = cluster_pools[chosen_cluster_id].pop()
            result_indices.append(sample_idx)
            remaining[chosen_cluster_id] -= 1

        # Return the balanced sequence of indices this index is ussed to sample from the dataset
        return result_indices




            
    def set_epoch(self, epoch):
        """MUST call this at start of each epoch!"""
        self.epoch = epoch


    def __len__(self):
        return self.epoch_size
    



#
# CUSTOM TRACKER
#


class Tracker:
    

    """
    Tracks training progress for step-based or epoch-based training loops.

    This class wraps a PyTorch DataLoader and provides:
      - Automatic tracking of steps, epochs, batches, and total samples seen.
      - Early stopping via the `self._stop_training` flag.
      - Progress printing with batch and step counters.
      - Flexible stopping: either after a fixed number of steps (`n_steps`) or epochs (`n_epochs`).
      - Handles both full and partial batches via the `drop_last` argument.

    Design notes:
      - Counters (`step`, `batch_in_epoch`, etc.) are incremented *before* yielding each batch,
        so progress reflects the batch currently being processed (1-based indexing).
      - The loop will always stop exactly at the requested number of steps or epochs, even if extra
        batches/epochs are available, thanks to internal checks and a safety buffer for step-based mode.
      - Explicit early stopping is supported by setting `self._stop_training = True` from anywhere.

    Args:
        dataloader (DataLoader): The PyTorch DataLoader to wrap.
        sampler (Sampler): The sampler used for epoch control.
        n_steps (int, optional): Stop after this many steps (batches). Mutually exclusive with n_epochs.
        n_epochs (int, optional): Stop after this many epochs. Mutually exclusive with n_steps.
        drop_last (bool): If True, only count full batches per epoch.

    Example:
        tracker = Tracker(dataloader, sampler, n_steps=1000)
        for epoch in tracker.epochs():
            for batch in tracker():
                # Training code...
                tracker.print_progress()
    """


    def __init__(self, dataloader, sampler, n_steps=None, n_epochs=None, drop_last=False):
        if n_steps is None and n_epochs is None:
            raise ValueError("Must specify either n_steps or n_epochs")
        if n_steps is not None and n_epochs is not None:
            raise ValueError("Specify only one: n_steps or n_epochs")
        
        self.dataloader = dataloader
        self.sampler = sampler
        self.n_steps = n_steps
        self.n_epochs = n_epochs
        self.drop_last = drop_last
        
        # Calculate dataset info
        epoch_size = len(sampler)
        batch_size = dataloader.batch_size
        self.batch_size = batch_size
        if drop_last:
            self.batches_per_epoch = epoch_size // batch_size
        else:
            self.batches_per_epoch = (epoch_size + batch_size - 1) // batch_size
        
        # Calculate max epochs needed
        if n_steps is not None:
            #with safety batch
            self.max_epochs = (n_steps // self.batches_per_epoch) + 2
            #precise
            #self.max_epochs = (n_steps + self.batches_per_epoch - 1) // self.batches_per_epoch
        else:
            self.max_epochs = n_epochs
        
        # Tracking state
        self.step = -1 # Start at -1 to make first batch 0 idx based, increment happens before yielding. 
        self.epoch = 0 
        self.total_samples_seen = 0
        self.batch_in_epoch = -1  # Start at -1 to make first batch 0 idx based, increment happens before yielding.
        self._stop_training = False
        self.avg_val_loss = None  # Placeholder for average validation loss if needed
        

    def resume(self, step, epoch, complete_epoch=True):
        #Raise if not starting from a complete epoch
        if complete_epoch:
            print("Tracker: Resuming from a complete epoch.")
            self.step = step
            self.epoch = epoch + 1  # <-- Start from the next epoch after the last completed one
        else:
            print('Tracker: Resuming from a non-complete epoch.')
            raise ValueError("Cannot resume from a non-complete epoch. Not implemented yet.")

    def epochs(self, fallback_max=999):
        """Iterator for epochs - uses calculated max or fallback"""
        max_epochs = self.max_epochs if hasattr(self, 'max_epochs') else fallback_max
        
        for epoch_num in range(self.epoch, max_epochs):
            if self._stop_training:
                break
                
            self.epoch = epoch_num
            self.batch_in_epoch = 0
            self.sampler.set_epoch(epoch_num)
            
            yield epoch_num
            
            # Stop if epoch-based and we've completed target epochs
            #if self.n_epochs is not None and epoch_num + 1 >= self.n_epochs:
            #   break
    
    def __call__(self, dataloader=None):
        """Make tracker callable to wrap dataloader"""
        dl = dataloader or self.dataloader
        
        for batch in dl:

            if self._stop_training:
                print("Tracker: Stopping training due to early stop flag.")
                break
                
            
            self.total_samples_seen += len(batch['pdb_id'])  # Assuming batch has pdb_id
            self.step += 1
            self.batch_in_epoch += 1

            yield batch

            
            # Check if we should stop (step-based)
            if self.n_steps is not None and self.step >= self.n_steps:
                self._stop_training = True
                break
    
    def print_progress(self, info=None):
        """Print current progress"""
        if self.n_steps:
            step_progress = f"Step {self.step+1}/{self.n_steps} ({100*(self.step+1)/self.n_steps:.1f}%)"
        else:
            step_progress = f"Step {self.step}"

        if hasattr(self, 'max_epochs') and self.max_epochs:
            epoch_progress = f"Epoch {self.epoch+1}/{self.max_epochs} ({100*(self.epoch+1)/self.max_epochs:.1f}%)"
        else:
            epoch_progress = f"Epoch {self.epoch}"

        print(f"{step_progress} | {epoch_progress}, Batch {self.batch_in_epoch + 1}/{self.batches_per_epoch} | "
              f"Samples seen: {self.total_samples_seen}")
        
        if info is not None:
            print(info)


    def get_progress(self):
        """Return current progress statistics as a dict for logging/monitoring."""
        progress = {
            'step': self.step,
            'steps_total': self.n_steps if self.n_steps else None,
            'step_percent': (100 * (self.step + 1) / self.n_steps) if self.n_steps else None,
            'epoch': self.epoch,  # 1-based for reporting
            'epochs_total': self.max_epochs if hasattr(self, 'max_epochs') else None,
            'epoch_percent': (100 * (self.epoch + 1) / self.max_epochs) if hasattr(self, 'max_epochs') and self.max_epochs else None,
            'batch_in_epoch': self.batch_in_epoch,
            'batches_per_epoch': self.batches_per_epoch,
            'batch_percent': (100 * (self.batch_in_epoch + 1) / self.batches_per_epoch) if self.batches_per_epoch else None,
            'samples_seen': self.total_samples_seen
        }
        return progress
    
    def save_checkpoint(self, model, optimizer, scheduler, config, ckpt_path, complete_epoch=False, extra=None):
            """
            Save a training checkpoint with all relevant state.
            Args:
                model: The model to save (should have .state_dict()).
                optimizer: The optimizer to save (should have .state_dict()).
                scheduler: The scheduler to save (should have .state_dict()).
                config: The config object/dict to save.
                ckpt_path: Path to save the checkpoint file.
                extra: Optional dict of extra fields to include in the checkpoint.
            """
            state = {
                'config': config,
                'model': model.state_dict(),
                'optimizer': optimizer.state_dict(),
                'scheduler': scheduler.state_dict(),
                'iteration': self.step,
                'step': self.step,
                'epoch': self.epoch,
                'tracker_progress': self.get_progress(),
                'complete_epoch': complete_epoch,
                'avg_val_loss': getattr(self, 'avg_val_loss', None),
            }
            if extra:
                state.update(extra)
            import torch
            torch.save(state, ckpt_path)

#
# VERIFICATION
#



def check_epoch_similarity(sampler, dataloader):
    """
    Check if the sampler generates different sequences for multiple epochs.
    Prints the sequences for the first few epochs to verify diversity.
    """
    num_epochs = 3
    sequences = []
    for epoch in range(num_epochs):
        sampler.set_epoch(epoch)
        sequence = list(iter(sampler))
        sequences.append(sequence)
        print(f"Epoch {epoch}: First 10 indices: {sequence[:10]}")
        print(f"Epoch {epoch}: Last 10 indices: {sequence[-10:]}")
        print(f"Epoch {epoch}: Sequence length: {len(sequence)}\n")

    # Compare sequences for diversity
    for i in range(num_epochs - 1):
        overlap = len(set(sequences[i]) & set(sequences[i+1]))
        print(f"Overlap between epoch {i} and {i+1}: {overlap} samples")



#
# EXAMPLE USAGE
#

dataset_config = EasyDict({
    "train": {
        "type": "sabdab_dgad",
        "summary_path": "./data/sabdab_summary_all.tsv",
        "chothia_dir": "./data/all_structures/chothia",
        "processed_dir": "./data/processed",
        "split": "train",
        "transform": [
            {"type": "mask_single_cdr_dgad", "selection": "H_CDR3"},
            {"type": "merge_chains"},
            {"type": "patch_around_anchor"}
        ]
    },
    "val": {
        "type": "sabdab_dgad",
        "summary_path": "./data/sabdab_summary_all.tsv",
        "chothia_dir": "./data/all_structures/chothia",
        "processed_dir": "./data/processed",
        "split": "val",
        "transform": [
            {"type": "mask_single_cdr_dgad", "selection": "CDR3"},
            {"type": "merge_chains"},
            {"type": "patch_around_anchor"}
        ]
    }
})



if __name__ == '__main__':
    # Example usage
    print("Loading dataset...")

    #For the base dataset

    # base_train_dataset = get_dataset(dataset_config["train"])
    # #Get the dataset via config
    
    # batch_size = 32
    # n_steps = 1000
    # print(f"Creating sampler...")
    # sampler = BalancedClusterSampler(base_train_dataset, 
    #                                  sampling_balance=0.5, 
    #                                  sampling_mixing=SamplingMixingMethod.LINEAR, 
    #                                  seed=70,
    #                                  multiplier=30)
   
    
    # print("Creating dataloader...")
    # dataloader = DataLoader(base_train_dataset, 
    #                         sampler=sampler, 
    #                         collate_fn=PaddingCollate(), 
    #                         batch_size=32, 
    #                         num_workers=0)
    
    # print("Creating tracker...")
    # tracker = Tracker(dataloader, sampler, n_steps=n_steps)

    # #check the sampler sequences for multiple epochs and check if they are different
    # #so print each sequences check it for a few epochs
    # #check_epoch_similarity(sampler, dataloader)
    
    # # n_steps, n_epochs, n_batch_in_epoch, n_samples
    
    # for epoch in tracker.epochs(100):
    #     sampler.set_epoch(epoch)
        
    #     for batch in tracker(dataloader):  # Tracker wraps the dataloader!
            
    #         # Process batch
    #         print(f"Epoch {epoch}, Batch size: {len(batch['pdb_id'])}")
    #         print('step: ', tracker.step)


    #         #
    #         # TRAIN
    #         #

            
    #         # Print progress anytime you want
    #         #if tracker.step % 100 == 0:
    #         tracker.print_progress()
    #             # Outputs: Step 100/1000 (10.0%) | Epoch 0, Batch 100/156 | Samples seen: 3200

        
    #     pass
    aux_dataset = AuxDataset(dataset_dir='./data_dgad/dgad_aux_dataset')


    # For the aux dataset
    sampler = BalancedClusterSampler(aux_dataset, 
                                        sampling_balance=1.0, 
                                        sampling_mixing=SamplingMixingMethod.LINEAR, 
                                        seed=70,
                                        multiplier=30)



    aux_data_loader = DataLoader(
        aux_dataset, 
        batch_size=4, 
        collate_fn=PaddingCollate(), 
        sampler=sampler,
        num_workers=0
    )

    tracker = Tracker(aux_data_loader, sampler, n_steps=1000)

    check_epoch_similarity(sampler, aux_data_loader)

    for epoch in tracker.epochs(100):
        sampler.set_epoch(epoch)
        for batch in tracker(aux_data_loader):
            # Process batch
            print(f"Aux Epoch {epoch}, Batch size: {len(batch['pdb_id'])}")
            print('step: ', tracker.step)
            print(batch['pos_heavyatom'].shape)

            # Print progress anytime you want
            #if tracker.step % 100 == 0:
            tracker.print_progress()
                # Outputs: Step 100/1000 (10.0%) | Epoch 0, Batch 100/156 | Samples seen: 3200

